apiVersion: batch/v1
kind: Job
metadata:
  name: selenium-test-job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: selenium-test
          image: meganraj/selenium-test:latest
          imagePullPolicy: Always
      restartPolicy: Never
